### ISSUE TITLE
System Argumentexception in CheckExistsAsync in Xamarin.Forms UWP Project

### ISSUE THREAD

**Issue by escamoteur** [dsplaisted/PCLStorage#33]
Hi,

I'm trying to port my Xamarin Forms Android App to UWP. Unfortunately I get this exception while trying to check if a file in exists (which it doesn't).

Two things irritate me. first why at all is an exception thrown, And why it's an 'System.ArgumentException.

I found out, that UWP unlike Android throws an exception if the directory of the file that is checked does not exist. 

```
'BREADy.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
The thread 0xb6c has exited with code 0 (0x0).
The thread 0x10a0 has exited with code 0 (0x0).
Step into: Stepping over non-user code 'BREADy.Model.FileStorage.CheckFileExists'
Step into: Stepping over non-user code 'BREADy.Model.FileStorage.<CheckFileExists>d__12..ctor'
The thread 0x124c has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll
WinRT information: Ein Element mit dem angegebenen Namen (ingredients/ingredients.json) kann nicht gefunden werden.
Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll
WinRT information: Ein Element mit dem angegebenen Namen (ingredients/ingredients.json) kann nicht gefunden werden.
Exception thrown: 'System.ArgumentException' in mscorlib.ni.dll
WinRT information: Ein Element mit dem angegebenen Namen (ingredients/ingredients.json) kann nicht gefunden werden.



   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PCLStorage.WinRTFolder.<CheckExistsAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BREADy.Model.FileStorage.<CheckFileExists>d__12.MoveNext()

```

**Comment by JKennedy24** [comment]
I am also getting this error when checking if a file exists on UWP
